### ISSUE TITLE
Is there any published paper describing your work?

### ISSUE THREAD

**Issue by ilya-palachev** [snunlp/KR-BERT#1]
Hello,

First of all, thank you for publishing this repository. Is there any published paper describing your work? I mean a paper in some journal or conference proceedings. This information would help to understand your work a lot.

Thanks in advance!

**Comment by hpshin** [comment]
HiYou can get the paper by clicking https://arxiv.org/abs/2008.03979The citation information in now on the github.BestHyopil Shin
Vice Dean of Academic Affairs, and Professor,  Graduate School of Data ScienceAffiliated Professor, Dept. of Linguistics
Seoul National University
82-2-880-1135(Office)
http://knlp.snu.ac.kr
--------- 원본 메일 ---------보낸사람 : Ilya Palachev <notifications@github.com>받는사람 : snunlp/KR-BERT <KR-BERT@noreply.github.com>참조 : Subscribed <subscribed@noreply.github.com>받은날짜 : 2020-08-10 (월) 15:14:41제목 : [snunlp/KR-BERT] Is there any published paper describing your work? (#1)
Hello,
First of all, thank you for publishing this repository. Is there any published paper describing your work? I mean a paper in some journal or conference proceedings. This information would help to understand your work a lot.
Thanks in advance!

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/snunlp/KR-BERT/issues/1",
"url": "https://github.com/snunlp/KR-BERT/issues/1",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by ilya-palachev** [comment]
Thank you very much @hpshin for uploading the paper! It is really useful for me.
